name: Python Test Workflow (Question I et III)

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [hello_world, hello_world2]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Notification start for ${{ matrix.script }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: 'Début des tests pour ${{ matrix.script }} sur la branche main'
          SLACK_COLOR: '#FFA500'  # Optional: change color as needed
      - name: Run pytest
        run: pytest
        working-directory: ./tests
      - name: Run script ${{ matrix.script }}
        run: python src/${{ matrix.script }}.py
      - name: Notification success for ${{ matrix.script }}
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: 'Tests réussis pour ${{ matrix.script }} sur la branche main'
          SLACK_COLOR: 'good'  # green
      - name: Notification failure for ${{ matrix.script }}
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: 'Échec des tests pour ${{ matrix.script }} sur la branche main'
          SLACK_COLOR: 'danger'  # red
